---
- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in pushgateway_web_listen_address"

- name: Fail on unsupported init systems
  fail:
    msg: "This module only works with systemd"
  when: ansible_service_mgr != 'systemd'

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    pushgateway_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"

- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/prometheus/pushgateway/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: true
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set pushgateway version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        pushgateway_version: "{{ _latest_release.json.tag_name[1:] }}"
  when: pushgateway_version == "latest"
  delegate_to: localhost
  run_once: true

- name: Get checksum list from repo
  set_fact:
    _checksums: "{{ lookup('url', pushgateway_download_url + pushgateway_version + '/sha256sums.txt', wantlist=True) | list }}"
  run_once: true
  delegate_to: localhost
  when: pushgateway_checksum is not defined

- name: "Get checksum for {{ go_arch }} architecture"
  set_fact:
    pushgateway_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ _checksums }}"
  when:
    - pushgateway_checksum is not defined
    - "('linux-' + go_arch + '.tar.gz') in item"


